"""Shared Gazebo rendering visibility-layer contract."""

GZ_VISIBILITY_ALL = 0x0FFFFFFF
STATIC_PASSAGE_MASS_VISIBILITY_FLAG = 0x08000000
NO_STATIC_OCCLUDER_VISIBILITY_FLAG = 0x04000000
DRONE_MARKER_VISIBILITY_FLAG = 0x02000000
SENSOR_COLLISION_PROXY_VISIBILITY_FLAG = 0x01000000

SENSOR_VISIBLE_WORLD_MASK = GZ_VISIBILITY_ALL & ~DRONE_MARKER_VISIBILITY_FLAG
STATIC_VISIBILITY_MASK = SENSOR_VISIBLE_WORLD_MASK & ~(
    STATIC_PASSAGE_MASS_VISIBILITY_FLAG | NO_STATIC_OCCLUDER_VISIBILITY_FLAG
)
NO_STATIC_3D_VISIBILITY_MASK = (
    SENSOR_VISIBLE_WORLD_MASK & ~NO_STATIC_OCCLUDER_VISIBILITY_FLAG
)
